### ISSUE TITLE
make agent.jar download optional

### ISSUE THREAD

**Issue by attachmentgenie** [jenkinsci/nomad-plugin#77]
### Feature Request

At the moment, it appears that the way the nomad (docker) job is started always tries to download the agent jar file. When using the upstream jenkins/agent image this isnt necessary

**Comment by j3t** [comment]
We could add a toggle to the worker template which indicates whether the agent.jar is downloaded (default: true) but then we have to provide a possibility to adjust the command and args as well which is probably very confusing and error prone.

I would suggest to rework the whole worker-template so that a JSON job template can be specified and then we don't need to all the form fields at all. What do you think?

**Comment by multani** [comment]
https://github.com/jenkinsci/nomad-plugin/pull/82 revamped the way jobs are submitted and they are now fully customizable: downloading the JAR agent can be optional now.
